# Generated by Django 6.1 on 2026-09-09 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_desk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My AWS Account', max_length=100)),
                ('access_key_id', models.CharField(max_length=255)),
                ('secret_access_key', models.CharField(max_length=255)),
                ('region', models.CharField(default='us-east-1', max_length=100)),
                ('account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_connections', to='cloud_desk.user')),
            ],
        ),
    ]
