# Generated by Django 6.1 on 2026-09-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_desk', '0005_gcpconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpconnection',
            name='service_account_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gcpconnection',
            name='service_account_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gcpconnection',
            name='name',
            field=models.CharField(default='My GCP Account', max_length=100),
        ),
    ]
