# Generated by Django 6.1 on 2026-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_desk', '0006_gcpconnection_service_account_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcpconnection',
            old_name='access_token',
            new_name='credentials_json',
        ),
        migrations.RemoveField(
            model_name='gcpconnection',
            name='google_email',
        ),
        migrations.RemoveField(
            model_name='gcpconnection',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='gcpconnection',
            name='service_account_json',
        ),
        migrations.RemoveField(
            model_name='gcpconnection',
            name='token_expiry',
        ),
        migrations.AlterField(
            model_name='gcpconnection',
            name='name',
            field=models.CharField(default='My GCP Project', max_length=100),
        ),
    ]
