# Generated by Django 6.1 on 2026-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_desk', '0007_rename_access_token_gcpconnection_credentials_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcpconnection',
            name='name',
            field=models.CharField(default='My GCP Account', max_length=100),
        ),
    ]
