name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: om0126/cloud_app:latest

   
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull om0126/cloud_app:latest
            sudo docker stop cloud_app || true
            sudo docker rm cloud_app || true
            sudo docker run -d \
              --name cloud_app \
              --restart unless-stopped \
              -p 8000:8000 \
              -e DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
              -e DJANGO_DEBUG="${{ secrets.DJANGO_DEBUG }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e EMAIL_HOST="${{ secrets.EMAIL_HOST }}" \
              -e EMAIL_PORT="${{ secrets.EMAIL_PORT }}" \
              -e EMAIL_USE_TLS="${{ secrets.EMAIL_USE_TLS }}" \
              -e EMAIL_HOST_USER="${{ secrets.EMAIL_HOST_USER }}" \
              -e EMAIL_HOST_PASSWORD="${{ secrets.EMAIL_HOST_PASSWORD }}" \
              om0126/cloud_app:latest
